"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Shell from "@/components/Shell";
import {supabaseBrowser} from "@/lib/supabase-browser";
import {getCurrentProfile} from "@/lib/current-user";

type Employee={id:string;full_name:string;email:string;phone:string;employee_code:string;role:"CEO"|"ADMIN"|"EMPLOYEE";active:boolean;created_at:string;updated_at?:string};
type Sale={id:string;employee_id:string;product_id:string;quantity:number;unit_price:number;cost_at_sale:number;total:number;profit:number;payment_method:string;sold_at:string;product?:{name:string;category:string}|null};
type Form={full_name:string;email:string;phone:string;employee_code:string;password:string;role:"EMPLOYEE"|"ADMIN"};
const blank:Form={full_name:"",email:"",phone:"",employee_code:"",password:"",role:"EMPLOYEE"};

export default function Employees(){
 const router=useRouter();
 const [me,setMe]=useState<any>(null); const [rows,setRows]=useState<Employee[]>([]); const [sales,setSales]=useState<Sale[]>([]);
 const [form,setForm]=useState<Form>(blank); const [edit,setEdit]=useState<Employee|null>(null); const [editForm,setEditForm]=useState<Form>(blank);
 const [selected,setSelected]=useState<Employee|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(""); const [search,setSearch]=useState("");
 async function token(){const {data}=await supabaseBrowser().auth.getSession();return data.session?.access_token||""}
 async function load(){
  const p=await getCurrentProfile(); setMe(p);
  if(!p || !["CEO","ADMIN"].includes(p.role)){router.replace("/dashboard");return;}
  const t=await token(); const res=await fetch("/api/employees",{headers:{Authorization:`Bearer ${t}`}}); const json=await res.json();
  if(!res.ok){setMsg(json.error||"Could not load employees");setLoading(false);return;}
  setRows(json.employees||[]);
  const {data,error}=await supabaseBrowser().from("sales").select("id,employee_id,product_id,quantity,unit_price,cost_at_sale,total,profit,payment_method,sold_at,products(name,category)").order("sold_at",{ascending:false});
  if(error) setMsg(error.message); else setSales((data||[]) as Sale[]);
  setLoading(false);
 }
 useEffect(()=>{load();const sb=supabaseBrowser();const ch=sb.channel("employees-live").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},load).on("postgres_changes",{event:"*",schema:"public",table:"sales"},load).subscribe();return()=>{sb.removeChannel(ch)}},[]);
 function setF(k:keyof Form,v:string){setForm(x=>({...x,[k]:v}))}
 async function createEmployee(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg("");try{const t=await token();const res=await fetch("/api/employees",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(form)});const json=await res.json();if(!res.ok)throw new Error(json.error);setMsg(`${form.role==="ADMIN"?"Administrator":"Employee"} created successfully.`);setForm(blank);await load()}catch(err){setMsg(err instanceof Error?err.message:"Could not create account.")}finally{setSaving(false)}}
 function openEdit(x:Employee){setEdit(x);setEditForm({full_name:x.full_name,email:x.email,phone:x.phone||"",employee_code:x.employee_code||"",password:"",role:x.role==="ADMIN"?"ADMIN":"EMPLOYEE"})}
 async function saveEdit(e:React.FormEvent){e.preventDefault();if(!edit)return;setSaving(true);setMsg("");try{const t=await token();const res=await fetch("/api/employees",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({...editForm,id:edit.id})});const json=await res.json();if(!res.ok)throw new Error(json.error);setMsg("Account updated successfully.");setEdit(null);await load()}catch(err){setMsg(err instanceof Error?err.message:"Could not update account.")}finally{setSaving(false)}}
 async function toggle(x:Employee){if(x.role==="ADMIN"&&me?.role!=="CEO")return alert("Only the CEO can manage an Administrator account.");if(!confirm(`${x.active?"Disable":"Enable"} ${x.full_name}?`))return;setSaving(true);try{const t=await token();const res=await fetch("/api/employees",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({id:x.id,active:!x.active})});const json=await res.json();if(!res.ok)throw new Error(json.error);setMsg(`${x.full_name} is now ${!x.active?"active":"disabled"}.`);await load()}catch(err){setMsg(err instanceof Error?err.message:"Could not change account status.")}finally{setSaving(false)}}
 async function remove(x:Employee){if(x.role==="ADMIN"&&me?.role!=="CEO")return alert("Only the CEO can delete an Administrator.");if(!confirm(`Permanently delete ${x.full_name}?\n\nIf this account has sales, the system will protect the sales history and ask you to disable the account instead.`))return;setSaving(true);setMsg("");try{const t=await token();const res=await fetch("/api/employees",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({id:x.id})});const json=await res.json();if(!res.ok)throw new Error(json.error);setMsg(`${x.full_name} was deleted.`);await load()}catch(err){setMsg(err instanceof Error?err.message:"Could not delete account.")}finally{setSaving(false)}}
 const filtered=useMemo(()=>rows.filter(x=>`${x.full_name} ${x.email} ${x.employee_code} ${x.phone}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 const stats=(id:string)=>{const now=new Date();const day=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();const week=day-6*86400000;const month=new Date(now.getFullYear(),now.getMonth(),1).getTime();const year=new Date(now.getFullYear(),0,1).getTime();const own=sales.filter(s=>s.employee_id===id);const calc=(from:number)=>({revenue:own.filter(s=>new Date(s.sold_at).getTime()>=from).reduce((a,s)=>a+Number(s.total||0),0),items:own.filter(s=>new Date(s.sold_at).getTime()>=from).reduce((a,s)=>a+Number(s.quantity||0),0),transactions:own.filter(s=>new Date(s.sold_at).getTime()>=from).length});return {day:calc(day),week:calc(week),month:calc(month),year:calc(year)}};
 const detail=selected?sales.filter(s=>s.employee_id===selected.id):[];
 const detailTotals=detail.reduce((a,s)=>({revenue:a.revenue+Number(s.total||0),profit:a.profit+Number(s.profit||0),items:a.items+Number(s.quantity||0),transactions:a.transactions+1}),{revenue:0,profit:0,items:0,transactions:0});
 return <Shell>
  <div className="pagehead"><div><h1>Employee Management</h1><p className="muted">Create accounts, manage access, and click any staff profile to see complete sales history.</p></div><div className="rolebadge">{me?.role}</div></div>
  {msg&&<div className="notice">{msg}</div>}
  <section className="card"><h2>Add Employee / Administrator</h2><form className="form grid-form" onSubmit={createEmployee}><input className="input" placeholder="Full name *" value={form.full_name} onChange={e=>setF("full_name",e.target.value)} required/><input className="input" type="email" placeholder="Email *" value={form.email} onChange={e=>setF("email",e.target.value)} required/><input className="input" placeholder="Phone" value={form.phone} onChange={e=>setF("phone",e.target.value)}/><input className="input" placeholder="Employee ID (e.g. RD-001)" value={form.employee_code} onChange={e=>setF("employee_code",e.target.value)}/><input className="input" type="password" minLength={8} placeholder="Temporary password (8+ chars) *" value={form.password} onChange={e=>setF("password",e.target.value)} required/><select className="select" value={form.role} onChange={e=>setF("role",e.target.value as Form["role"])} disabled={me?.role!=="CEO"}><option value="EMPLOYEE">Employee</option><option value="ADMIN">Administrator</option></select><button className="btn primary" disabled={saving}>{saving?"Saving...":"Create Account"}</button></form><p className="muted small">CEO can create Employees and Administrators. ADMIN can create Employees only.</p></section>
  <section className="card" style={{marginTop:16}}><div className="tablehead"><div><h2>Staff Accounts</h2><p className="muted small">Click a person's name to open their full sales profile.</p></div><input className="input search" placeholder="Search name, email or ID" value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<p>Loading employees...</p>:<div className="tablewrap"><table><thead><tr><th>Employee</th><th>Contact</th><th>Role</th><th>Status</th><th>Today</th><th>This Month</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=>{const s=stats(x.id);const canManage=me?.role==="CEO"||x.role!=="ADMIN";return <tr key={x.id}><td><button className="linkbtn" onClick={()=>setSelected(x)}><b>{x.full_name||"Unnamed"}</b></button><div className="muted small">{x.employee_code||"No ID"}</div></td><td>{x.email}<div className="muted small">{x.phone||"No phone"}</div></td><td><span className="tag">{x.role}</span></td><td><span className={x.active?"status active":"status inactive"}>{x.active?"Active":"Disabled"}</span></td><td>{s.day.revenue.toFixed(2)} Birr<div className="muted small">{s.day.transactions} sales • {s.day.items} items</div></td><td>{s.month.revenue.toFixed(2)} Birr<div className="muted small">{s.month.transactions} sales</div></td><td>{x.role!=="CEO"&&canManage?<><button className="btn" onClick={()=>openEdit(x)}>Edit</button> <button className={x.active?"btn danger":"btn success"} onClick={()=>toggle(x)} disabled={saving}>{x.active?"Disable":"Enable"}</button> <button className="btn danger" onClick={()=>remove(x)} disabled={saving}>Delete</button></>:<span className="muted small">CEO protected</span>}</td></tr>})}</tbody></table>{filtered.length===0&&<p className="muted">No employees found.</p>}</div>}</section>
  {edit&&<div className="modalback"><div className="modal"><div className="tablehead"><h2>Edit Account</h2><button className="btn" onClick={()=>setEdit(null)}>✕</button></div><form className="form" onSubmit={saveEdit}><label>Full name<input className="input" value={editForm.full_name} onChange={e=>setEditForm(x=>({...x,full_name:e.target.value}))} required/></label><label>Email<input className="input" type="email" value={editForm.email} onChange={e=>setEditForm(x=>({...x,email:e.target.value}))} required/></label><label>Phone<input className="input" value={editForm.phone} onChange={e=>setEditForm(x=>({...x,phone:e.target.value}))}/></label><label>Employee ID<input className="input" value={editForm.employee_code} onChange={e=>setEditForm(x=>({...x,employee_code:e.target.value}))}/></label><label>Role<select className="select" value={editForm.role} onChange={e=>setEditForm(x=>({...x,role:e.target.value as Form["role"]}))} disabled={me?.role!=="CEO"}><option value="EMPLOYEE">Employee</option><option value="ADMIN">Administrator</option></select></label><label>New password (optional)<input className="input" type="password" minLength={8} placeholder="Leave blank to keep current" value={editForm.password} onChange={e=>setEditForm(x=>({...x,password:e.target.value}))}/></label><div className="form"><button className="btn primary" disabled={saving}>{saving?"Saving...":"Save Changes"}</button><button type="button" className="btn" onClick={()=>setEdit(null)}>Cancel</button></div></form></div></div>}
  {selected&&<div className="modalback"><div className="modal wide"><div className="tablehead"><div><h2>{selected.full_name}</h2><p className="muted">{selected.employee_code||"No employee ID"} • {selected.role} • {selected.active?"Active":"Disabled"}</p></div><button className="btn" onClick={()=>setSelected(null)}>✕</button></div><div className="cards"><div className="card"><div>Total Transactions</div><div className="metric">{detailTotals.transactions}</div></div><div className="card"><div>Items Sold</div><div className="metric">{detailTotals.items}</div></div><div className="card"><div>Total Sales</div><div className="metric">{detailTotals.revenue.toFixed(2)} Birr</div></div><div className="card"><div>Gross Profit</div><div className="metric">{detailTotals.profit.toFixed(2)} Birr</div></div></div><h3 style={{marginTop:20}}>Complete Sales History</h3>{detail.length===0?<p className="muted">No sales recorded for this employee yet.</p>:<div className="tablewrap"><table><thead><tr><th>Date & Time</th><th>Product</th><th>Qty</th><th>Unit Price</th><th>Total</th><th>Profit</th><th>Payment</th></tr></thead><tbody>{detail.map(s=><tr key={s.id}><td>{new Date(s.sold_at).toLocaleString()}</td><td>{s.product?.name||"Product"}</td><td>{s.quantity}</td><td>{Number(s.unit_price).toFixed(2)} Birr</td><td>{Number(s.total).toFixed(2)} Birr</td><td>{Number(s.profit).toFixed(2)} Birr</td><td>{s.payment_method}</td></tr>)}</tbody></table></div>}</div></div>}
 </Shell>
}
